### ISSUE TITLE
Template variables

### ISSUE THREAD

**Issue by awunnenb** [julianlam/nodebb-plugin-registration-notification#5]
is this plugin working with nodebb 1.7.x?
the variables user.name and user.email are empty in then admin email.

**Comment by julianlam** [comment]
Hello there,

Yes, the plugin seems to work fine in my local testing. The HTML is generated appropriately:

```
<p>Hello,</p>                                                                                                                                                       [6/1804]

<p>
        <a href="https://localhost/forum/user/teafruit"><img style="vertical-align: middle; width: 24px; height: 24px; padding-right: 1em;" src="" title="teafruit" /></a>
        <a href="https://localhost/forum/user/teafruit">teafruit</a> has just registered on <strong>NodeBB</strong>!
</p>
<p>
        For your reference, their email address is <code>t@v.com</code>
</p>

<p>
        Thanks,<br />
        <strong>NodeBB</strong>
</p>

<hr />
<p>
        You are receiving this email because you have instructed NodeBB to send you an email every time a new user registers.
        <a href="https://localhost/forum/admin/plugins/registration-notification">Change those settings here</a>.
</p>
```

**Comment by julianlam** [comment]
Let me know if you're still experiencing issues.

**Comment by awunnenb** [comment]
this is my:

Mime-Version: 1.0

<p>Hallo,</p>

<p>
	<a href="https://www.bla.de/user/"><img style="vertical-align: middle; width: 24px; height: 24px; padding-right: 1em;" src="" title="" /></a>
	<a href="https://www.bla.de/user/"></a> has just registered on <strong>bla.de</strong>!
</p>
<p>
	For your reference, their email address is <code></code>
</p>

<p>
	Thanks,<br />
	<strong>bla.de</strong>
</p>

The vars are empty

**Comment by awunnenb** [comment]
it's not working with 1.7.4
The template variables are empty.
These are my used plugins:
...
"nodebb-plugin-composer-default": "6.0.8",
    "nodebb-plugin-dbsearch": "2.0.9",
    "nodebb-plugin-emailer-mailgun": "^1.0.2",
    "nodebb-plugin-emoji": "2.0.9",
    "nodebb-plugin-emoji-android": "2.0.0",
    "nodebb-plugin-markdown": "8.2.2",
    "nodebb-plugin-mentions": "2.2.2",
    "nodebb-plugin-registration-notification": "^1.2.1",
    "nodebb-plugin-soundpack-default": "1.0.0",
    "nodebb-plugin-spam-be-gone": "^0.5.3",
    "nodebb-rewards-essentials": "0.0.11",
    "nodebb-theme-lavender": "5.0.1",
    "nodebb-theme-persona": "7.2.16",
    "nodebb-theme-slick": "1.1.4",
    "nodebb-theme-vanilla": "8.1.7",
    "nodebb-widget-essentials": "4.0.1",
...

**Comment by julianlam** [comment]
Check the email templates in settings -> email -- has the registration notification template been modified? You may want to try resetting it back to the default and rebuild/restarting NodeBB.

**Comment by awunnenb** [comment]
<p>[[email:greeting_no_name]],</p>

<p>
	<a href="{url}/user/{user.userslug}"><img style="vertical-align: middle; width: 24px; height: 24px; padding-right: 1em;" src="{user.picture}" title="{user.username}" /></a>
	<a href="{url}/user/{user.userslug}">{user.name}</a> has just registered on <strong>{site_title}</strong>!
</p>
<p>
	For your reference, their email address is <code>{user.email}</code>
</p>

<p>
	Thanks,<br />
	<strong>{site_title}</strong>
</p>

<hr />
<p>
	You are receiving this email because you have instructed NodeBB to send you an email every time a new user registers.
	<a href="{url}/admin/plugins/registration-notification">Change those settings here</a>.
</p>
