### ISSUE TITLE
Email works but all user variables from template are empty

### ISSUE THREAD

**Issue by awunnenb** [julianlam/nodebb-plugin-registration-notification#7]
the email notification works but all user variables are empty (user.username, user.email, user.userslug, user.picture). All these variables are empty in received emails.

Only the variable site_title works fine in my received emails.

Register Setting: Admin approval

**Comment by julianlam** [comment]
Can you give v1.2.3 a try and see if it resolves the issue? Thanks.

**Comment by awunnenb** [comment]
where can i found  v1.2.3 ?

**Comment by julianlam** [comment]
npm :+1:

**Comment by awunnenb** [comment]
v1.2.3 works fine. Thank you!
