### ISSUE TITLE
Change `utils.slugify` to `slugify`

### ISSUE THREAD

**Issue by oplik0** [julianlam/nodebb-plugin-registration-notification#9]
`utils.slugify` was removed in 1.16 (https://github.com/NodeBB/NodeBB/issues/8808, https://github.com/NodeBB/NodeBB/commit/4a0d883359405d819e08e0ec1cad12cfaa81a772).

`utils` isn't used for anything else than `slugify`, so it's a simple change

**Comment by julianlam** [comment]
#10
